// src/components/app/NarrativeDisplay.tsx
"use client";

import { Card, CardContent, CardDescription, CardHeader, CardTitle, CardFooter } from "@/components/ui/card";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Separator } from "@/components/ui/separator";
import { BotMessageSquare, Volume2 } from "lucide-react";
import { useEffect, useRef } from "react";

interface NarrativeDisplayProps {
  narrativeText: string;
  audioDataUri: string;
}

export function NarrativeDisplay({ narrativeText, audioDataUri }: NarrativeDisplayProps) {
  const audioRef = useRef<HTMLAudioElement>(null);

  useEffect(() => {
    // Autoplay or handle audio element changes if necessary
    if (audioRef.current) {
      audioRef.current.load(); // Reload audio if src changes
      // audioRef.current.play().catch(e => console.warn("Audio autoplay blocked:", e));
    }
  }, [audioDataUri]);
  
  return (
    <Card className="shadow-lg w-full">
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <BotMessageSquare className="h-6 w-6 text-primary" />
          <span>Your Personalized Tour</span>
        </CardTitle>
        <CardDescription>
          Listen to the generated narrative for your selected location.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div>
          <h3 className="font-semibold mb-2 flex items-center gap-2">
            <Volume2 className="h-5 w-5 text-secondary" />
            Audio Narration
          </h3>
          {audioDataUri ? (
            <audio ref={audioRef} controls src={audioDataUri} className="w-full">
              Your browser does not support the audio element.
            </audio>
          ) : (
            <p className="text-sm text-muted-foreground">Audio is being processed or is unavailable.</p>
          )}
        </div>
        <Separator />
        <div>
          <h3 className="font-semibold mb-2">Narrative Text</h3>
          <ScrollArea className="h-60 w-full rounded-md border p-4 bg-background">
            <p className="text-sm whitespace-pre-wrap">{narrativeText || "No narrative text available."}</p>
          </ScrollArea>
        </div>
      </CardContent>
      <CardFooter>
        <p className="text-xs text-muted-foreground">
            Audio generated by AI. Enjoy your virtual tour!
        </p>
      </CardFooter>
    </Card>
  );
}
